pre-commit:
  parallel: true
  commands:
    prettier:
      run: npx prettier --write {staged_files}
    eslint:
      run: npx eslint --fix {staged_files}
pre-push:
  parallel: true
  commands:
    format:
      run: npm run format
    lint:
      run: npm run lint
